version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
      - "2345:2345" # Debugger
    extra_hosts:
      - "localhost:host-gateway"
